// Fixed bilingual (JA first, then EN) LINE reply templates for Jev-routed intents (see docs/JEV.md).
// Deterministic strings only -- never generated by an LLM. Keep INTENTS in sync with the `intent` Choice
// criteria built in web/src/app/api/line/webhook/route.ts.
import { LIFF_BASE_URL } from './plots';

export const INTENTS = [
  'payout_status',
  'why_held',
  'verify_identity',
  'request_slot',
  'trigger_explanation',
  'talk_to_coop',
  'other',
] as const;

export type Intent = (typeof INTENTS)[number];

const bilingual = (ja: string, en: string): string => `${ja}\n\n${en}`;

// TODO: payout_status currently points at the relative /donate path (no canonical deployed origin exists
// in this codebase yet -- see .env.example). Prefix with the real origin once the app is deployed.
const TEMPLATES: Record<Intent, string> = {
  payout_status: bilingual(
    '支払い状況は寄付台帳でご確認いただけます: /donate\n対象の支払いがあれば、この LINE に通知が届きます。',
    'You can check payout status on the public donor ledger: /donate. If a payment is due for your plot, you will get a notification here.',
  ),
  why_held: bilingual(
    `支払いが保留になる主な理由は、本人確認 (World ID) が未完了であることです。こちらから確認できます: ${LIFF_BASE_URL}`,
    `Payouts are most often held pending identity verification (World ID). You can complete it here: ${LIFF_BASE_URL}`,
  ),
  verify_identity: bilingual(
    `本人確認はこちらから行えます: ${LIFF_BASE_URL}`,
    `You can verify your identity here: ${LIFF_BASE_URL}`,
  ),
  request_slot: bilingual(
    `区画の登録・請求はこちらから行えます: ${LIFF_BASE_URL}`,
    `You can register or claim your plot slot here: ${LIFF_BASE_URL}`,
  ),
  trigger_explanation: bilingual(
    '支払いは、海水温や規制日数などの指標が基準値を超えると自動的に発生します。詳しい計算根拠は近日公開予定です。',
    'Payouts trigger automatically when an index (like sea temperature or ban-days) crosses a set threshold. A full breakdown is coming soon -- ask the co-op for specifics in the meantime.',
  ),
  talk_to_coop: bilingual(
    '承知しました。組合に確認し、折り返しご連絡します。',
    "Got it -- we'll check with the co-op and get back to you.",
  ),
  other: bilingual(
    'メッセージを受け取りました。組合が確認し、折り返しご連絡します。',
    "We've received your message. The co-op will review it and get back to you.",
  ),
};

/** The fixed reply for a confidently-classified intent. */
export function intentTemplate(intent: Intent): string {
  return TEMPLATES[intent];
}

/** The fallback reply when Jev's top choice doesn't clear the confidence threshold (or Jev is unavailable). */
export function escalationTemplate(): string {
  return bilingual(
    'メッセージを受け取りました。組合が確認し、折り返しご連絡します。',
    'Thanks for reaching out. The co-op will review your message and get back to you.',
  );
}
