// REFERENCE_FIRES must be what RULES give on the pipeline's real JAXA SST series at the reference point
// (pipeline/tests/heat/snapshots/kesennuma-sst-2022-2025.csv, regenerated by the pipeline's regression test).
// If the pipeline's SST conventions change (README Q10), the snapshot changes and this test says so.
import { expect, test } from 'bun:test';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { evaluateRules, type SeriesDay } from '../src/compute';
import { REFERENCE_FIRES } from '../src/rules';

const SNAPSHOT = join(import.meta.dir, '../../../pipeline/tests/heat/snapshots/kesennuma-sst-2022-2025.csv');

function seasonDays(season: string): SeriesDay[] {
  const [header, ...rows] = readFileSync(SNAPSHOT, 'utf8').trim().split('\n');
  const cols = header!.split(',');
  const date = cols.indexOf('date');
  const sst = cols.indexOf('sst');
  return rows
    .map((line) => line.split(','))
    .filter((r) => r[date]!.startsWith(season))
    .map((r) => ({ date: r[date]!, value: r[sst] === '' ? null : Number(r[sst]) }));
}

for (const season of Object.keys(REFERENCE_FIRES)) {
  test(`REFERENCE_FIRES ${season} matches RULES on the pipeline's JAXA SST snapshot`, () => {
    // Trigger v2: evaluateRules takes the daily SST series directly and applies each HEAT rule's tempC.
    const fired = evaluateRules(seasonDays(season));
    expect(Object.fromEntries(fired.map((f) => [f.label, f.firedOn]))).toEqual(REFERENCE_FIRES[season as keyof typeof REFERENCE_FIRES]);
  });
}
